import Articleitems from "@/components/articles/Articleitems";
import Pagination from "@/components/articles/Pagination";
import SareshAericals from "@/components/articles/SarechArtices";
import { Article } from "@/utils/type";
import type { Metadata } from "next";

const Articles = async () => {
  // Simulating network delay for demonstration purposes.
  await new Promise((resolve) => setTimeout(resolve, 2000));
  const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
    cache: "no-store" /* {next:{revalidate:50}}*/,
  });

  if (!response.ok) {
    throw new Error("Failed to fetch data...");
  }

  const data: Article[] = await response.json();

  return (
    <section className="fix-hight container m-auto px-5">
      <SareshAericals />
      <div className="flex items-center justify-center flex-wrap gap-7 ">
        {data.slice(0, 6).map((items) => (
          <Articleitems key={items.id} articals={items} />
        ))}
      </div>
      <Pagination />
    </section>
  );
};

export default Articles;
export const metadata: Metadata = {
  title: "Articles",
  description: "Generated by create next app",
};
